version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into AWS ECR
      - REPOSITORY_URI=282865065290.dkr.ecr.us-east-1.amazonaws.com/cursoddd02
      - aws ecr get-login-password | docker login --username AWS --password-stdin ${REPOSITORY_URI}
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=lastest}
      - ENVIRONMENT=$(echo $environment)
  build:
    commands:
      - echo Build started on `date`
      - aws s3 cp s3://cursoddd/$ENVIRONMENT/.env .env
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build complete on `date`
      - echo Pushing the docker image
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
artifacts:
  files:
    - 'Dockerrun.aws.json'
