version: '3.7'

services:
  mysql:
    image: mysql:8
    container_name: arq-mysql
    ports:
      - '3310:3306'
    environment:
      MYSQL_USER: user-cursosdev
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: cursosdev
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - vol-arq-mysql:/var/lib/mysql
    networks:
      - arq-net

  redis-server:
    image: redis:6.0.5-alpine
    container_name: redis-server2
    command: redis-server
    ports:
      - '6390:6379'
    restart: always
    networks:
      - arq-net

  redis-client:
    image: rediscommander/redis-commander:latest
    container_name: redis-client2
    ports:
      - '8090:8081'
    restart: always
    environment:
      - REDIS_HOSTS=local:redis-server2:6379
    depends_on:
      - redis-server
    networks:
      - arq-net

  app:
    build: .
    container_name: arq-app
    ports:
      - '5100:80'
    networks:
      - arq-net

volumes:
  vol-arq-mysql:

networks:
  arq-net:
